[project]
name = "first-mcp-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "amirhd4", email = "amir0hd4@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]==2.3.0",
    "openai-agents>=0.23.1",
    "psutil>=7.2.2",
]

[project.scripts]
first-mcp-project = "first_mcp_project:main"

[build-system]
requires = ["uv_build>=0.12.24,<0.13.0"]
build-backend = "uv_build"
